services:
  postgresql:
    container_name: medium-postgresql
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - 5432:5432
    volumes:
      - postgresqldb_data:/data/db/postgresql
volumes:
  postgresqldb_data: